import pandas as pd

df = pd.read_csv('data/data_cleaned.csv', na_values=['NA'])
print("Gender : ", df['Gender'].unique())
print("work_interfere : ", df['work_interfere'].unique())
print('self_employed : ', df['self_employed'].unique())
print('mental_health_consequence :', df['mental_health_consequence'].unique())
print('phys_health_consequence :', df['phys_health_consequence'].unique())
print('coworkers : ', df['coworkers'].unique())
print('supervisor :', df['supervisor'].unique())
print('benefits : ', df['benefits'].unique())
print('seek_help : ', df['seek_help'].unique())
print('remote_work : ', df['remote_work'].unique())
print('tech_company : ', df['tech_company'].unique())
print('mental_health_interview :', df['mental_health_interview'].unique())
print('mental_vs_physical : ', df['mental_vs_physical'].unique())
print('obs_consequence : ', df['obs_consequence'].unique())
print('treatment : ', df['treatment'].unique())
print("Family History : ", df['family_history'].unique())
